### ISSUE TITLE
Macro gets scl-ized even if in comment (and prefixed with %)

### ISSUE THREAD

**Issue by torsava** [sclorg/spec2scl#19]
Originally reported by: **Pavel Valena (Bitbucket: [pvalena](https://bitbucket.org/pvalena), GitHub: [pvalena](https://github.com/pvalena))**

----------------------------------------

```
# %%gem_install - this is a comment
```

becomes 

```
# %%{?scl:scl enable %{scl} - << \EOF}
%gem_install
%{?scl:EOF}
 - this is a comment
```

----------------------------------------
- Bitbucket: https://bitbucket.org/bkabrda/spec2scl/issue/19

**Comment by irushchyshyn** [comment]
Hi @pvalena, thanks for reporting the issue. However, I find it difficult to reproduce it. scl-izing comments seems to have been fixed in #7.

I understand that it's been a long time, but if you are still facing this issue, could you please provide a bit more details?
These three pieces of info should be enough:
- spec file you tried to convert
- `spec2scl` command options supplied
- spec2scl version used

Many thanks in advance.

**Comment by pvalena** [comment]
Hello,
I can confirm it has been fixed. Tested with

spec2scl-1.1.0a-2.el7.centos.noarch
&
spec2scl-1.1.3-3.fc24.noarch

Thanks!

**Comment by irushchyshyn** [comment]
Perfect, thanks for reply.
Closing the issue.
